// <auto-generated />
using System;
using KnowledgeHub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeHub.Server.Migrations
{
    [DbContext(typeof(KnowledgeHubDbContext))]
    partial class KnowledgeHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadMessages");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.ConversationThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UriReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSourceId", "UriReference")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoSyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.ToolApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResumedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("KnowledgeHub.Server.Domain.Entities.ConversationThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("KnowledgeHub.Server.Domain.Entities.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("KnowledgeHub.Server.Domain.Entities.KnowledgeSource", "Source")
                        .WithMany("Documents")
                        .HasForeignKey("KnowledgeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.ConversationThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("KnowledgeHub.Server.Domain.Entities.KnowledgeSource", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
